## Docs
# - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    reviewers:
      - "natterstefan"
    directory: "/"
    schedule:
      interval: "weekly"
      # Check for npm updates on Mondays
      day: "monday"
      # Check for npm updates at 3am UTC
      time: "03:00"
    open-pull-requests-limit: 10
    # Raise all npm pull requests with custom labels
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # For all packages, ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
