# Config file of .github/workflows/pr-label-commenter.yml workflow

comment:
  # header: Hi!
  footer: "\
    ---\n\n\
    > This is an automated comment. \
    Responding to the bot or mentioning it won't have any effect."

labels:
  - name: wontfix
    labeled:
      issue:
        body: This will not be worked on but we appreciate your contribution.
        action: close
    unlabeled:
      issue:
        body: This has become active again.
        action: open

  - name: duplicate
    labeled:
      issue:
        body: This issue already exists.
        action: close

  - name: good first issue
    labeled:
      issue:
        body: This issue is easy for contributing. Everyone can work on this.
