# inspired by https://github.com/peaceiris/actions-label-commenter/blob/b29c85e430e50b3a0b8251a0dcc77c3e74f4c7b8/.github/ISSUE_TEMPLATE/3_proposal.yml
name: Feature Request
description: Suggest a new feature for this project.
title: "feat: "
labels: enhancement
assignees: natterstefan
body:
  - type: markdown
    attributes:
      value:
        Please note we will close your issue without comment if you do not fill
        out the issue checklist below and provide ALL the requested information.
  - type: checkboxes
    attributes:
      label: Checklist
      description: Checklist before creating an issue.
      options:
        - label: "I am using the latest version."
          required: true
        - label: "I have read the latest README and followed the instructions."
          required: true
  - type: textarea
    attributes:
      label: "Describe your feature request"
      description:
        "A clear and concise description of what the featur request is about."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
      description:
        "A clear and concise description of any alternative solutions or
        features you've considered."
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Additional context"
      description:
        "Add any other context or screenshots about the feature request here."
    validations:
      required: false
