name: Misc First Interaction

on: [workflow_call, workflow_dispatch, pull_request, issues]

permissions:
  contents: read

jobs:
  main:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # @see https://github.com/actions/first-interaction
      - uses: actions/first-interaction@64bdb230668432c6ad905f3080df6d00e4d32229
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message:
            "Hello\nLooks like this is the first issue you created."
          pr-message:
            "Hello\nLooks like this is the first pull request you created."
