# @see https://github.com/kentaro-m/auto-assign-action
name: PR Auto Assign

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read

jobs:
  check-auto-assign:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: kentaro-m/auto-assign-action@0f54499433a7c535289cdb1aad8d4bc9a64bd192
