name: PR Checklist

on: [workflow_call, workflow_dispatch, pull_request]

jobs:
  checklist:
    permissions:
      # required for actions/checkout (@see https://github.com/actions/checkout/issues/254#issuecomment-899182888)
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2

      # @see https://github.com/wyozi/contextual-qa-checklist-action
      - uses: wyozi/contextual-qa-checklist-action@c063201bfa7fe8e9f72fb70ed2fe8cc0718c34c6
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
