name: PR Checklist

on: [workflow_call, workflow_dispatch, pull_request_target]

jobs:
  checklist:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # @see https://github.com/marketplace/actions/contextual-qa-checklists
      - name: Checklist
        uses: wyozi/contextual-qa-checklist-action@27696c9016d0f9759baaccd2cf5f3002c38d3801
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
