name: PR Completed Checklists

on: [workflow_call, workflow_dispatch, pull_request, issues]

jobs:
  review-checklists:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # @see https://github.com/mheap/require-checklist-action
      - uses: mheap/require-checklist-action@e711a3246e9ecbeb6bddb7c8b0fc7ee8b5e1ba24
        with:
          # If this is true and there are no checklists detected, the action
          # will fail
          requireChecklist: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
