name: PR Checklist

on: [workflow_call, workflow_dispatch, pull_request]

permissions: read-all

jobs:
  checklist:
    permissions:
      # for actions/checkout to fetch code
      # @see https://github.com/actions/checkout/issues/254#issuecomment-899182888
      # @see https://github.com/actions/checkout/pull/653
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      # @see https://github.com/wyozi/contextual-qa-checklist-action
      - uses: wyozi/contextual-qa-checklist-action@0386969e2cd9899b3d808e1edcf2852128b44063
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
