# @see https://github.com/actions/labeler
name: PR Labeler

on: [workflow_call, workflow_dispatch, pull_request]

permissions:
  contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/labeler@e54e5b338fbd6e6cdb5d60f51c22335fc57c401e
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
