name: PR Approved Label

on: [workflow_call, workflow_dispatch, pull_request]

permissions:
  contents: read

jobs:
  check-merge-conflict:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # @see https://github.com/eps1lon/actions-label-merge-conflict
      - uses: eps1lon/actions-label-merge-conflict@b2a593dbcdeb6a66cf2afd543fe416a5688f93ef
        with:
          # By default, pull requests from a fork do not have access to the
          # Secrets and are given a Github token with read permission, which
          # means that the tags cannot be updated.
          continueOnMissingPermissions: true
          dirtyLabel: "needs rebase"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty:
            "This pull request has conflicts, please resolve those first before
            requesting a review of the pull request."
