# @see https://github.com/TimonVS/pr-labeler-action
name: PR Branch Labeler

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened]

permissions:
  contents: read

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      # @see https://github.com/TimonVS/pr-labeler-action/issues/58
      pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    steps:
      # SHA mentioned in https://github.com/TimonVS/pr-labeler-action/issues/33
      - uses: TimonVS/pr-labeler-action@bd0b592a410983316a454e3d48444608f028ec8e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
