# @see https://github.com/peaceiris/actions-label-commenter
name: PR Label Commenter

## NOTE
# How to work with other labeler actions?
# @see https://github.com/peaceiris/actions-label-commenter#work-with-other-auto-label-actions

on:
  workflow_call:
  workflow_dispatch:
  issues:
    types: [labeled, unlabeled]
  pull_request:
    types: [labeled, unlabeled]
  discussion:
    types: [labeled, unlabeled]

permissions:
  contents: read

jobs:
  label-commenter:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      # hash taken from here: https://github.com/peaceiris/actions-label-commenter/blob/b29c85e430e50b3a0b8251a0dcc77c3e74f4c7b8/.github/workflows/label-commenter.yml#L27
      - uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579
