# @see https://github.com/lannonbr/issue-label-manager-action
#
# Alternatives
# @see https://github.com/micnncim/action-label-syncer (supports sync with other
# repository)
name: Repo Label Management

on: [workflow_call, workflow_dispatch, pull_request, issues]

permissions:
  contents: read

jobs:
  labels:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: lannonbr/issue-label-manager-action@e8dbcd8198e86a1e98d5372e55db976fed9ba6f7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # will delete any labels that aren't in the .github/labels.json
          delete: true
